version: '3.9'

services:
  # databases
  postgres:
    image: postgres:16-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - ${APP_DIR}/database/cameras-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -h ${POSTGRES_HOST}"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 30s
  redis:
    image: redis:8.6.3-alpine
    env_file: .env
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}
    command: redis-server --save "" --appendonly no --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "--user", "${REDIS_USER}", "--pass", "${REDIS_PASSWORD}", "-h", "${REDIS_HOST}", "-p", "${REDIS_PORT}", "-n", "${REDIS_DB}", "ping"]    
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 5s
  migrate:
    image: migrate/migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${APP_DIR}/database/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable",
      "up"
    ]
    restart: on-failure

  # stream handling
  mediamtx:
    image: bluenviron/mediamtx:latest
    restart: unless-stopped
    volumes:
      - ${APP_DIR}/mediamtx/mediamtx.yml:/mediamtx.yml
    ports:
      - 8554:8554
      - 8322:8322
      - 1935:1935
      - 8888:8888
      - 8889:8889
    profiles: ["mediamtx"]

  # application
  backend:
    build: ./backend
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"